name: Build Kernel

on:
  push:
    branches: [ lineage-18.1 ]
  pull_request:
    branches: [ lineage-18.1 ]
    
env:
  DEFCONFIG_NAME: lineageos_crosshatch_defconfig
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install build-essential cpio liblz4-dev zipalign p7zip fakeroot gcc make bc curl git zip
      
       - name: Clone Build ToolChain
         run: |
            git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git Toolchain
       
       - name: "Checkout kernel source"
         uses: actions/checkout@v2
         
       - name: "Make Kernel"
         run: |
            cd android_kernel_google_msm-4.9
            export ARCH=arm64
            export SUBARCH=arm64
            export CROSS_COMPILE=aarch64-linux-android-
            export PATH=../Toolchain/bin
            make $DEFCONFIG_NAME
            make
